// Mocks generated by Mockito 5.2.0 from annotations
// in numismatist/test/unit_tests/repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:numismatist/api/dto/catalog_dto.dart' as _i5;
import 'package:numismatist/api/dto/item_dto.dart' as _i6;
import 'package:numismatist/api/dto/lastupdate_dto.dart' as _i2;
import 'package:numismatist/repository/models/catalog.dart' as _i7;
import 'package:numismatist/repository/models/currency.dart' as _i9;
import 'package:numismatist/repository/models/item.dart' as _i8;

import '../impls/client_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeLastUpdateDto_0 extends _i1.Fake implements _i2.LastUpdateDto {}

class _FakeDateTime_1 extends _i1.Fake implements DateTime {}

/// A class which mocks [RestClientImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestClientImpl extends _i1.Mock implements _i3.RestClientImpl {
  MockRestClientImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.CatalogDto>> catalogs() =>
      (super.noSuchMethod(Invocation.method(#catalogs, []), returnValue: Future<List<_i5.CatalogDto>>.value(<_i5.CatalogDto>[])) as _i4.Future<List<_i5.CatalogDto>>);
  @override
  _i4.Future<List<_i6.ItemDto>> items(String? id) =>
      (super.noSuchMethod(Invocation.method(#items, [id]), returnValue: Future<List<_i6.ItemDto>>.value(<_i6.ItemDto>[])) as _i4.Future<List<_i6.ItemDto>>);
  @override
  _i4.Future<_i2.LastUpdateDto> lastUpdate() =>
      (super.noSuchMethod(Invocation.method(#lastUpdate, []), returnValue: Future<_i2.LastUpdateDto>.value(_FakeLastUpdateDto_0())) as _i4.Future<_i2.LastUpdateDto>);
}

/// A class which mocks [Catalog].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalog extends _i1.Mock implements _i7.Catalog {
  MockCatalog() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  String get name => (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  String get description => (super.noSuchMethod(Invocation.getter(#description), returnValue: '') as String);
  @override
  DateTime get lastUpdate => (super.noSuchMethod(Invocation.getter(#lastUpdate), returnValue: _FakeDateTime_1()) as DateTime);
  @override
  List<String> get items => (super.noSuchMethod(Invocation.getter(#items), returnValue: <String>[]) as List<String>);
}

/// A class which mocks [Item].
///
/// See the documentation for Mockito's code generation for more information.
class MockItem extends _i1.Mock implements _i8.Item {
  MockItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  String get catalogId => (super.noSuchMethod(Invocation.getter(#catalogId), returnValue: '') as String);
  @override
  String get name => (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  String get description => (super.noSuchMethod(Invocation.getter(#description), returnValue: '') as String);
  @override
  num get nominal => (super.noSuchMethod(Invocation.getter(#nominal), returnValue: 0) as num);
  @override
  _i9.Currency get currency => (super.noSuchMethod(Invocation.getter(#currency), returnValue: _i9.Currency.RUR) as _i9.Currency);
  @override
  String get material => (super.noSuchMethod(Invocation.getter(#material), returnValue: '') as String);
  @override
  List<int> get years => (super.noSuchMethod(Invocation.getter(#years), returnValue: <int>[]) as List<int>);
  @override
  List<String> get facilities => (super.noSuchMethod(Invocation.getter(#facilities), returnValue: <String>[]) as List<String>);
  @override
  DateTime get lastUpdate => (super.noSuchMethod(Invocation.getter(#lastUpdate), returnValue: _FakeDateTime_1()) as DateTime);
}

/// A class which mocks [CatalogDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogDto extends _i1.Mock implements _i5.CatalogDto {
  @override
  String get id => (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(Invocation.method(#toJson, []), returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}

/// A class which mocks [ItemDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemDto extends _i1.Mock implements _i6.ItemDto {
  @override
  String get id => (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  String get name => (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  num get nominal => (super.noSuchMethod(Invocation.getter(#nominal), returnValue: 0) as num);
  @override
  int get currency => (super.noSuchMethod(Invocation.getter(#currency), returnValue: 0) as int);
  @override
  String get material => (super.noSuchMethod(Invocation.getter(#material), returnValue: '') as String);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(Invocation.method(#toJson, []), returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}
