name: homework_4
description: Homework for lession 04.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon_back.svg
    - assets/images/icon_hart.svg
    - assets/images/icon_out.svg
  fonts:
   - family: SF Pro Text
     fonts:
       - asset: assets/fonts/SF-Pro-Text-Regular.otf
         weight: 500
   - family: SF Pro
     fonts:
       - asset: assets/fonts/SF-Pro.ttf
         weight: 500
   - family: ABeeZee
     fonts:
       - asset: assets/fonts/ABeeZee-Regular.ttf
         weight: 400
