name: lesson_17
description: Databases in Flutter
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  hive: ^2.0.4
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  sqflite: ^2.0.0+3
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.2


flutter:
  uses-material-design: true