name: lesson_18
description: Application State
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  get_it: ^7.1.3
  injectable: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  pedantic: ^1.11.0
  injectable_generator: ^1.4.0