name: cocktail_app_tests
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
  http: ^0.13.4
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.0
  mockito: ^5.2.0
  equatable: ^2.0.3
  mocktail_image_network: ^0.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  test: ^1.21.1

flutter:
  uses-material-design: true

